FROM ubuntu:22.04

ARG PHP_VER=8.2
ENV DEBIAN_FRONTEND=noninteractive

# Bring in base packages & Ondřej PPA and PHP modules via helper scripts
COPY ./files/base_packages.sh /docker_build/base_packages.sh
COPY ./files/php/bin_install_modules.sh /docker_build/bin_install_modules.sh
COPY ./files/php/bin_clean_directories.sh /docker_build/bin_clean_directories.sh

RUN set -eux;         chmod +x /docker_build/base_packages.sh /docker_build/bin_install_modules.sh /docker_build/bin_clean_directories.sh;         /docker_build/base_packages.sh;         /docker_build/bin_install_modules.sh ${PHP_VER};         /docker_build/bin_clean_directories.sh ${PHP_VER};         rm -rf /var/lib/apt/lists/*

# Default command for smoke tests
CMD ["php","-v"]
